[package]
name = "worktree-io"
version = "0.6.2"
edition = "2021"
description = "A CLI tool to open GitHub issues as git worktree workspaces"
license = "MIT"

[lib]
name = "worktree_io"
path = "src/lib.rs"

[[bin]]
name = "worktree"
path = "src/main.rs"

[dev-dependencies]
cargo-husky = { version = "1", default-features = false, features = ["user-hooks"] }

[dependencies]
clap    = { version = "4", features = ["derive"] }
serde   = { version = "1", features = ["derive"] }
toml    = "0.8"
anyhow  = "1"
url     = "2"
dirs    = "5"
